server {
    listen 80;
    listen [::]:80;
    server_name chuncui.icu;

    return 301 https://blog.chuncui.icu$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name chuncui.icu;

    ssl_certificate /etc/letsencrypt/live/blog.chuncui.icu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/blog.chuncui.icu/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://blog.chuncui.icu$request_uri;
}
